

CREATE FUNCTION FATCA.CleanAccents (@Text NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
    DECLARE @CleanedText NVARCHAR(MAX)
    SET @CleanedText = @Text COLLATE Latin1_General_CI_AI

    -- Handle German characters
    SET @CleanedText = REPLACE(@CleanedText, 'ß', 'ss')
    SET @CleanedText = REPLACE(@CleanedText, 'Ä', 'Ae')
    SET @CleanedText = REPLACE(@CleanedText, 'ä', 'ae')
    SET @CleanedText = REPLACE(@CleanedText, 'Ö', 'Oe')
    SET @CleanedText = REPLACE(@CleanedText, 'ö', 'oe')
    SET @CleanedText = REPLACE(@CleanedText, 'Ü', 'Ue')
    SET @CleanedText = REPLACE(@CleanedText, 'ü', 'ue')

    -- Handle French characters
    SET @CleanedText = REPLACE(@CleanedText, 'Œ', 'OE')
    SET @CleanedText = REPLACE(@CleanedText, 'œ', 'oe')
    SET @CleanedText = REPLACE(@CleanedText, 'Ç', 'C')
    SET @CleanedText = REPLACE(@CleanedText, 'ç', 'c')
    SET @CleanedText = REPLACE(@CleanedText, 'É', 'E')
    SET @CleanedText = REPLACE(@CleanedText, 'é', 'e')

    -- Handle Scandinavian characters
    SET @CleanedText = REPLACE(@CleanedText, 'Ø', 'O')
    SET @CleanedText = REPLACE(@CleanedText, 'ø', 'o')
    SET @CleanedText = REPLACE(@CleanedText, 'Å', 'Aa')
    SET @CleanedText = REPLACE(@CleanedText, 'å', 'aa')
    SET @CleanedText = REPLACE(@CleanedText, 'Æ', 'Ae')
    SET @CleanedText = REPLACE(@CleanedText, 'æ', 'ae')

    -- Handle Polish characters
    SET @CleanedText = REPLACE(@CleanedText, 'Ł', 'L')
    SET @CleanedText = REPLACE(@CleanedText, 'ł', 'l')
    SET @CleanedText = REPLACE(@CleanedText, 'Ś', 'S')
    SET @CleanedText = REPLACE(@CleanedText, 'ś', 's')
    SET @CleanedText = REPLACE(@CleanedText, 'Ź', 'Z')
    SET @CleanedText = REPLACE(@CleanedText, 'ź', 'z')
    SET @CleanedText = REPLACE(@CleanedText, 'Ż', 'Z')
    SET @CleanedText = REPLACE(@CleanedText, 'ż', 'z')
    SET @CleanedText = REPLACE(@CleanedText, 'Ń', 'N')
    SET @CleanedText = REPLACE(@CleanedText, 'ń', 'n')
    SET @CleanedText = REPLACE(@CleanedText, 'Ć', 'C')
    SET @CleanedText = REPLACE(@CleanedText, 'ć', 'c')
    SET @CleanedText = REPLACE(@CleanedText, 'Ę', 'E')
    SET @CleanedText = REPLACE(@CleanedText, 'ę', 'e')
    SET @CleanedText = REPLACE(@CleanedText, 'Ą', 'A')
    SET @CleanedText = REPLACE(@CleanedText, 'ą', 'a')

    -- Handle Spanish characters
    SET @CleanedText = REPLACE(@CleanedText, 'Ñ', 'N')
    SET @CleanedText = REPLACE(@CleanedText, 'ñ', 'n')

    -- Handle Czech and Slovak characters
    SET @CleanedText = REPLACE(@CleanedText, 'Č', 'C')
    SET @CleanedText = REPLACE(@CleanedText, 'č', 'c')
    SET @CleanedText = REPLACE(@CleanedText, 'Š', 'S')
    SET @CleanedText = REPLACE(@CleanedText, 'š', 's')
    SET @CleanedText = REPLACE(@CleanedText, 'Ř', 'R')
    SET @CleanedText = REPLACE(@CleanedText, 'ř', 'r')
    SET @CleanedText = REPLACE(@CleanedText, 'Ž', 'Z')
    SET @CleanedText = REPLACE(@CleanedText, 'ž', 'z')
    SET @CleanedText = REPLACE(@CleanedText, 'Ď', 'D')
    SET @CleanedText = REPLACE(@CleanedText, 'ď', 'd')
    SET @CleanedText = REPLACE(@CleanedText, 'Ť', 'T')
    SET @CleanedText = REPLACE(@CleanedText, 'ť', 't')
    SET @CleanedText = REPLACE(@CleanedText, 'Ň', 'N')
    SET @CleanedText = REPLACE(@CleanedText, 'ň', 'n')
    SET @CleanedText = REPLACE(@CleanedText, 'Ě', 'E')
    SET @CleanedText = REPLACE(@CleanedText, 'ě', 'e')
    SET @CleanedText = REPLACE(@CleanedText, 'Ů', 'U')
    SET @CleanedText = REPLACE(@CleanedText, 'ů', 'u')

    -- Handle Hungarian characters
    SET @CleanedText = REPLACE(@CleanedText, 'Ő', 'O')
    SET @CleanedText = REPLACE(@CleanedText, 'ő', 'o')
    SET @CleanedText = REPLACE(@CleanedText, 'Ű', 'U')
    SET @CleanedText = REPLACE(@CleanedText, 'ű', 'u')

    -- Handle Turkish characters
    SET @CleanedText = REPLACE(@CleanedText, 'Ş', 'S')
    SET @CleanedText = REPLACE(@CleanedText, 'ş', 's')
    SET @CleanedText = REPLACE(@CleanedText, 'İ', 'I')
    SET @CleanedText = REPLACE(@CleanedText, 'ı', 'i')
    SET @CleanedText = REPLACE(@CleanedText, 'Ğ', 'G')
    SET @CleanedText = REPLACE(@CleanedText, 'ğ', 'g')
    SET @CleanedText = REPLACE(@CleanedText, 'Ç', 'C')
    SET @CleanedText = REPLACE(@CleanedText, 'ç', 'c')

    -- Handle basic Russian Cyrillic transliteration
    SET @CleanedText = REPLACE(@CleanedText, N'А', 'A')
    SET @CleanedText = REPLACE(@CleanedText, N'а', 'a')
    SET @CleanedText = REPLACE(@CleanedText, N'Б', 'B')
    SET @CleanedText = REPLACE(@CleanedText, N'б', 'b')
    SET @CleanedText = REPLACE(@CleanedText, N'В', 'V')
    SET @CleanedText = REPLACE(@CleanedText, N'в', 'v')
    SET @CleanedText = REPLACE(@CleanedText, N'Г', 'G')
    SET @CleanedText = REPLACE(@CleanedText, N'г', 'g')
    SET @CleanedText = REPLACE(@CleanedText, N'Д', 'D')
    SET @CleanedText = REPLACE(@CleanedText, N'д', 'd')
    SET @CleanedText = REPLACE(@CleanedText, N'Е', 'E')
    SET @CleanedText = REPLACE(@CleanedText, N'е', 'e')
    SET @CleanedText = REPLACE(@CleanedText, N'Ё', 'E')
    SET @CleanedText = REPLACE(@CleanedText, N'ё', 'e')
    SET @CleanedText = REPLACE(@CleanedText, N'Ж', 'Zh')
    SET @CleanedText = REPLACE(@CleanedText, N'ж', 'zh')
    SET @CleanedText = REPLACE(@CleanedText, N'З', 'Z')
    SET @CleanedText = REPLACE(@CleanedText, N'з', 'z')
    SET @CleanedText = REPLACE(@CleanedText, N'И', 'I')
    SET @CleanedText = REPLACE(@CleanedText, N'и', 'i')
    SET @CleanedText = REPLACE(@CleanedText, N'Й', 'Y')
    SET @CleanedText = REPLACE(@CleanedText, N'й', 'y')
    SET @CleanedText = REPLACE(@CleanedText, N'К', 'K')
    SET @CleanedText = REPLACE(@CleanedText, N'к', 'k')
    SET @CleanedText = REPLACE(@CleanedText, N'Л', 'L')
    SET @CleanedText = REPLACE(@CleanedText, N'л', 'l')
    SET @CleanedText = REPLACE(@CleanedText, N'М', 'M')
    SET @CleanedText = REPLACE(@CleanedText, N'м', 'm')
    SET @CleanedText = REPLACE(@CleanedText, N'Н', 'N')
    SET @CleanedText = REPLACE(@CleanedText, N'н', 'n')
    SET @CleanedText = REPLACE(@CleanedText, N'О', 'O')
    SET @CleanedText = REPLACE(@CleanedText, N'о', 'o')
    SET @CleanedText = REPLACE(@CleanedText, N'П', 'P')
    SET @CleanedText = REPLACE(@CleanedText, N'п', 'p')
    SET @CleanedText = REPLACE(@CleanedText, N'Р', 'R')
    SET @CleanedText = REPLACE(@CleanedText, N'р', 'r')
    SET @CleanedText = REPLACE(@CleanedText, N'С', 'S')
    SET @CleanedText = REPLACE(@CleanedText, N'с', 's')
    SET @CleanedText = REPLACE(@CleanedText, N'Т', 'T')
    SET @CleanedText = REPLACE(@CleanedText, N'т', 't')
    SET @CleanedText = REPLACE(@CleanedText, N'У', 'U')
    SET @CleanedText = REPLACE(@CleanedText, N'у', 'u')
    SET @CleanedText = REPLACE(@CleanedText, N'Ф', 'F')
    SET @CleanedText = REPLACE(@CleanedText, N'ф', 'f')
    SET @CleanedText = REPLACE(@CleanedText, N'Х', 'Kh')
    SET @CleanedText = REPLACE(@CleanedText, N'х', 'kh')
    SET @CleanedText = REPLACE(@CleanedText, N'Ц', 'Ts')
    SET @CleanedText = REPLACE(@CleanedText, N'ц', 'ts')
    SET @CleanedText = REPLACE(@CleanedText, N'Ч', 'Ch')
    SET @CleanedText = REPLACE(@CleanedText, N'ч', 'ch')
    SET @CleanedText = REPLACE(@CleanedText, N'Ш', 'Sh')
    SET @CleanedText = REPLACE(@CleanedText, N'ш', 'sh')
    SET @CleanedText = REPLACE(@CleanedText, N'Щ', 'Shch')
    SET @CleanedText = REPLACE(@CleanedText, N'щ', 'shch')
    SET @CleanedText = REPLACE(@CleanedText, N'Ы', 'Y')
    SET @CleanedText = REPLACE(@CleanedText, N'ы', 'y')
    SET @CleanedText = REPLACE(@CleanedText, N'Э', 'E')
    SET @CleanedText = REPLACE(@CleanedText, N'э', 'e')
    SET @CleanedText = REPLACE(@CleanedText, N'Ю', 'Yu')
    SET @CleanedText = REPLACE(@CleanedText, N'ю', 'yu')
    SET @CleanedText = REPLACE(@CleanedText, N'Я', 'Ya')
    SET @CleanedText = REPLACE(@CleanedText, N'я', 'ya')

    RETURN @CleanedText
END
